version: "3.7"

# mkdir -p /usr/local/var/howtocards/preview-images
##
## issue certificate with let's encrypt
# mkdir -p /usr/local/var/howtocards/tls
# openssl dhparam -out /usr/local/var/howtocards/tls/dhparam.pem 2048

## Latest deploy: 2020-02-21T16:28:28.294Z2

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/howtocards/preview-images"
      o: bind

services:
  public-api:
    image: docker.pkg.github.com/howtocards/backend/public-api:dev

  internal-api:
    image: docker.pkg.github.com/howtocards/backend/internal-api:dev

  frontend:
    image: docker.pkg.github.com/howtocards/frontend/frontend:dev

  # admin:
  #   image: docker.pkg.github.com/howtocards/admin/admin:dev

  ssi:
    build:
      args:
        FRONTEND_VERSION: dev
        SSI_VERSION: dev
    environment:
      - PUBLIC_URL=https://cards-dev.atomix.team/
      - IMAGE_URL=https://cards-dev.atomix.team/images

  entry:
    networks:
      entry:
        aliases:
          - cards-dev.atomix.team
    volumes:
      - /etc/letsencrypt/live/cards-dev.atomix.team/fullchain.pem:/var/lib/howtocards/tls/howtocards.crt
      - /etc/letsencrypt/live/cards-dev.atomix.team/privkey.pem:/var/lib/howtocards/tls/howtocards.pem
      - /usr/local/var/howtocards/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem

  preview-queue:
    image: docker.pkg.github.com/howtocards/preview-queue/preview-queue:dev

  image-uploader:
    image: docker.pkg.github.com/howtocards/image-uploader/image-uploader:dev

  preview-worker-1:
    image: docker.pkg.github.com/howtocards/preview-worker/preview-worker:dev
    environment:
      POOL_SIZE: "2"
      RENDER_HOST: "https://cards-dev.atomix.team"
