version: "3.7"

services:
  public-api:
    image: howtocards/public-api:dev

  frontend:
    image: howtocards/frontend:dev

  ssi:
    build:
      args:
        FRONTEND_VERSION: dev
        SSI_VERSION: dev
    environment:
      - PUBLIC_URL=http://test.cards.atomix.team/

  entry:
    volumes:
      - /etc/letsencrypt/live/test.cards.atomix.team/fullchain.pem:/var/lib/howtocards/tls/howtocards.crt
      - /etc/letsencrypt/live/test.cards.atomix.team/privkey.pem:/var/lib/howtocards/tls/howtocards.pem
      - /usr/local/var/howtocards/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem
