version: "3.7"

services:
  public-api:
    image: howtocards/public-api:dev

  frontend:
    image: howtocards/frontend:dev

  ssi:
    build:
      args:
        FRONTEND_VERSION: dev
        SSI_VERSION: dev
    environment:
      - PUBLIC_URL=http://test.cards.atomix.team/
