version: "3.7"

services:
  db:
    container_name: howtocards-database
    image: postgres:11.5
    restart: always
    volumes:
      - /usr/local/var/howtocards/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"

  public-api:
    container_name: howtocards-public-api
    image: howtocards/public-api:latest
    restart: always
    expose:
      - "9000"
    links:
      - db
    depends_on:
      - db
    environment:
      - RUST_LOG=info
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}

  frontend:
    container_name: howtocards-frontend
    image: howtocards/frontend:latest
    expose:
      - "80"

  ssi:
    container_name: howtocards-ssi
    image: howtocards-ssi
    build:
      context: ./ssi
      dockerfile: Dockerfile
      args:
        FRONTEND_VERSION: latest
        SSI_VERSION: latest
    restart: always
    expose:
      - "4000"
    links:
      - public-api
    depends_on:
      - public-api
    environment:
      - RUST_LOG=info
      - PUBLIC_URL=https://howtocards.io
      - BACKEND_URL=http://public-api:9000
      - LISTEN_HOST=0.0.0.0:4000

  entry:
    container_name: howtocards-entry
    image: howtocards-entry
    build:
      context: ./entry
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - ssi
      - frontend
      - public-api
    depends_on:
      - ssi
      - frontend
      - public-api
    volumes:
      - /usr/local/var/howtocards/tls:/var/lib/howtocards/tls
      - /usr/local/var/howtocards/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem
