name: Dev CI

on:
  push:
    paths:
      - "docker-compose.yaml"
      - "docker-compose.dev.yaml"
      - ".github/workflows/dev.yml"
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SSH
      uses: appleboy/ssh-action@v0.0.7
      env:
        POSTGRES_DB: ${{ secrets.DEV_DB }}
        POSTGRES_USER: ${{ secrets.DEV_DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        RELEASE_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DEV_DOCKER_USERNAME }}
      with:
        host: ${{ secrets.DEV_HOSTNAME }}
        username: ${{ secrets.DEV_USER }}
        port: ${{ secrets.DEV_PORT }}
        key: ${{ secrets.DEV_SSH_PRIVATE }}
        passphrase: ${{ secrets.DEV_SSH_PASSPHRASE }}
        envs: POSTGRES_DB,POSTGRES_USER,POSTGRES_PASSWORD,RELEASE_SHA,GITHUB_TOKEN,DOCKER_USERNAME
        script_stop: true
        script: |
          cd releases
          git reset --hard HEAD
          git clean -f
          git fetch -p
          git checkout $RELEASE_SHA
          echo "$POSTGRES_PASSWORD" > ~/database-password.txt
          docker login docker.pkg.github.com --username $DOCKER_USERNAME -p $GITHUB_TOKEN
          docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml build
          docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d --remove-orphans
